# Generated by Django 4.2.4 on 2023-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='genres',
            field=models.ManyToManyField(to='main_app.genre'),
        ),
    ]
