# Generated by Django 4.2.4 on 2023-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_creditcard_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='img_url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
    ]
